### ISSUE TITLE
Test failure: WebSocketMiddlewareTests.CloseFromCloseSent_Success

### ISSUE THREAD

**Issue by cesarbs** [aspnet/WebSockets#127]
```
    Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.CloseFromCloseSent_Success [FAIL]
      System.Net.WebSockets.WebSocketException : An internal WebSocket error occurred. Please see the innerException, if present, for more details.
      ---- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
      Stack Trace:
           at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boole    an aborted)
           at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        WebSocketMiddlewareTests.cs(492,0): at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<CloseFromCloseSent_Success>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace -----
           at System.Net.WebSockets.WebSocketConnectionStream.WebSocketConnection.ReadAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken canc    ellationToken, Boolean ignoreReadError)
           at System.Net.WebSockets.WebSocketConnectionStream.WebSocketConnection.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancella    tionToken)
           at System.Net.DelegatedStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
           at System.Net.BufferedReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
           at System.Net.WebSockets.WebSocketConnectionStream.<>n__0(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
           at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
```

**Comment by cesarbs** [comment]
Another one:

```
    Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.CloseFromCloseSent_Success [FAIL]
      System.Net.WebSockets.WebSocketException : The remote party closed the WebSocket connection without completing the close handshake.
      Stack Trace:
           at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        WebSocketMiddlewareTests.cs(492,0): at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<CloseFromCloseSent_Success>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by anurse** [comment]
When did these errors occur? I'm seeing all the tests passing right now.

**Comment by cesarbs** [comment]
They were occurring very consistently on my machine. Let me check again.

**Comment by cesarbs** [comment]
Interesting, I'm not seeing the failures anymore. Maybe they were fixed by a recent change? I was seeing them every time I ran the build script when I filed this issue.

**Comment by anurse** [comment]
The code that handles this phase of the connection is all code we grab from CoreFX and haven't changed in a while, so I'm not sure what would cause the issue. We'll keep an eye out for it for now.
