### ISSUE TITLE
1.1.3 Flaky test in OSX

### ISSUE THREAD

**Issue by pranavkm** [aspnet/WebSockets#163]
AutobahnTests.AutobahnTestSuite 	

```
 System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.CurlException : Couldn't connect to server
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

I think we made a bunch of changes in dev to fix these tests. I guess we'll need to port this over

**Comment by pranavkm** [comment]
cc @Eilon \ @anurse  \ @muratg

**Comment by Tratcher** [comment]
@anurse

**Comment by anurse** [comment]
Probably. We made the tests more resilient to slow agents, because we were seeing problems in macOS

**Comment by anurse** [comment]
Should be resolved now.
