### ISSUE TITLE
Unexpected end of stream - Should be close?

### ISSUE THREAD

**Issue by benaadams** [aspnet/WebSockets#63]
```
fail: AgeOfAscent.Space.SpaceWebSocketsMiddleware[1]
      PlayerWebsocket error System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unexpected end of stream
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<CompleteReceiveTaskAsync>d__57.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 311
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<ReceiveProcessAsync>d__54.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 276
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<ReceiveAsync>d__53.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 266
         --- End of inner exception stack trace ---
      ---> (Inner Exception #0) System.IO.IOException: Unexpected end of stream
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<CompleteReceiveTaskAsync>d__57.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 311
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<ReceiveProcessAsync>d__54.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 276
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at AgeOfAscent.Web.Network.PlayerWebsocket.<ReceiveAsync>d__53.MoveNext() in I:\IllyriadGames.AgeOfAscent\src\AgeOfAscent.Space\Network\PlayerWebsocket.cs:line 266<---
```

**Comment by Tratcher** [comment]
How did you hit this?

**Comment by benaadams** [comment]
I think hard disconnects rather than close messages

**Comment by benaadams** [comment]
I think hard disconnects rather than close messages; can recreate easily by connecting via websockets with a client then terminating it.

**Comment by benaadams** [comment]
It didn't do anything untoward - other than being very messy for the error log

**Comment by benaadams** [comment]
Feels a bit like this sort of state: https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/Owin/WebSockets/WebSocketHandler.cs#L237

Is a disconnect rather than an error

**Comment by Tratcher** [comment]
Oh so it's behaving as expected, it's just noisy. A disconnect is an error in the WebSocket protocol, it's just not a very interesting one. We can check the flow and see if it can be simplified.

**Comment by benaadams** [comment]
Yea, agreed, but its a bit like someone disconnecting mid http download - probably don't care too much; whereas a `fail` is like a "go investigate what's wrong" type thing. Could be a `debug`, `verbose` or even just "disconnected" type report?

**Comment by muratg** [comment]
Moving out, though would be happy to accept a PR :)

**Comment by ergen** [comment]
I get the same error. I read most of the links but I could not understand how to handle it.  I publish my application and send data to the client. it works. then I disconnect the client without closing browser (like unplugging network cable) and try sending again it fails. I use try catch and looks ok but then I get this error in log file. should I detect the users who are not used to close their browsers and block them from the application.. I add this [link ](http://stackoverflow.com/questions/41154770/prevent-application-crashes-when-sending-data-over-a-closed-websocket-connection) here because of GitHub does not let vote down
